# Generated by Django 3.0.8 on 2020-07-21 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('initial_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('por validar', 'por validar'), ('validado', 'validado'), ('resolvido', 'resolvido')], default='por validar', max_length=100)),
                ('category', models.CharField(choices=[('CONSTRUCTION', 'CONSTRUCTION'), ('SPECIAL_EVENT', 'SPECIAL_EVENT'), ('INCIDENT', 'INCIDENT'), ('WEATHER_CONDITION', 'WEATHER_CONDITION'), ('ROAD_CONDITION', 'ROAD_CONDITION')], max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
